logo: /assets/img/logo.gif
description: An Add'On for <a href="https://www.kerbalspaceprogram.com" target="_blank">Kerbal Space Program</a>.
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap